/**
 * Calm sounds. Every file is generated by scripts/generate-sounds.sh from
 * filtered noise, tones and timed events — no recordings, so there are no
 * licences to track — and each is a seamless loop, bundled with the app so it
 * plays offline.
 *
 * Café and Morning Birds are wanted too, but voices and birdsong need real
 * recordings; they are added when licence-clean ones are found.
 */

export type Sound = {
  key: string;
  name: string;
  /** One line under the name. */
  note: string;
  asset: number;
};

export type SoundCategory = {
  key: string;
  label: string;
  sounds: readonly Sound[];
};

export const SOUND_CATEGORIES: readonly SoundCategory[] = [
  {
    key: 'rain',
    label: 'rain',
    sounds: [
      { key: 'gentle-rain', name: 'Gentle Rain', note: 'steady and soft', asset: require('../../../assets/sounds/gentle-rain.m4a') },
      { key: 'rain-on-window', name: 'Rain on Window', note: 'heard from inside', asset: require('../../../assets/sounds/rain-on-window.m4a') },
      { key: 'rain-thunder', name: 'Rain + Thunder', note: 'with a distant rumble', asset: require('../../../assets/sounds/rain-thunder.m4a') }
    ]
  },
  {
    key: 'water',
    label: 'water',
    sounds: [
      { key: 'calm-ocean', name: 'Calm Ocean', note: 'slow, deep swells', asset: require('../../../assets/sounds/calm-ocean.m4a') },
      { key: 'gentle-waves', name: 'Gentle Waves', note: 'small waves on a shore', asset: require('../../../assets/sounds/gentle-waves.m4a') },
      { key: 'forest-stream', name: 'Forest Stream', note: 'running water', asset: require('../../../assets/sounds/forest-stream.m4a') }
    ]
  },
  {
    key: 'nature',
    label: 'nature',
    sounds: [
      { key: 'forest', name: 'Forest', note: 'wind through leaves', asset: require('../../../assets/sounds/forest.m4a') },
      { key: 'gentle-wind', name: 'Gentle Wind', note: 'rising and falling', asset: require('../../../assets/sounds/gentle-wind.m4a') },
      { key: 'night-forest', name: 'Night Forest', note: 'crickets and a low breeze', asset: require('../../../assets/sounds/night-forest.m4a') }
    ]
  },
  {
    key: 'cozy',
    label: 'cozy',
    sounds: [
      { key: 'fireplace', name: 'Fireplace', note: 'embers and the odd pop', asset: require('../../../assets/sounds/fireplace.m4a') },
      { key: 'campfire', name: 'Campfire', note: 'crackling, outdoors', asset: require('../../../assets/sounds/campfire.m4a') },
      { key: 'cozy-cabin', name: 'Cozy Cabin', note: 'a fire inside, rain outside', asset: require('../../../assets/sounds/cozy-cabin.m4a') }
    ]
  },
  {
    key: 'noise',
    label: 'noise',
    sounds: [
      { key: 'white', name: 'White', note: 'bright and even', asset: require('../../../assets/sounds/white.m4a') },
      { key: 'pink', name: 'Pink', note: 'softer, like steady rain', asset: require('../../../assets/sounds/pink.m4a') },
      { key: 'brown', name: 'Brown', note: 'deep, like a far waterfall', asset: require('../../../assets/sounds/brown.m4a') },
      { key: 'fan', name: 'Fan', note: 'a low hum and whir', asset: require('../../../assets/sounds/fan.m4a') }
    ]
  },
  {
    key: 'ambient',
    label: 'ambient',
    sounds: [
      { key: 'library', name: 'Library', note: 'a quiet room, a page now and then', asset: require('../../../assets/sounds/library.m4a') },
      { key: 'city-night', name: 'City Night', note: 'distant traffic', asset: require('../../../assets/sounds/city-night.m4a') },
      { key: 'train', name: 'Train', note: 'rumble and the rhythm of the rails', asset: require('../../../assets/sounds/train.m4a') }
    ]
  },
  {
    key: 'sleep',
    label: 'sleep',
    sounds: [
      { key: 'rainy-night', name: 'Rainy Night', note: 'dark rain, far thunder', asset: require('../../../assets/sounds/rainy-night.m4a') },
      { key: 'ocean-at-night', name: 'Ocean at Night', note: 'slow waves, faint crickets', asset: require('../../../assets/sounds/ocean-at-night.m4a') },
      { key: 'deep-sleep', name: 'Deep Sleep', note: 'low noise and a quiet drone', asset: require('../../../assets/sounds/deep-sleep.m4a') }
    ]
  },
  {
    key: 'meditation',
    label: 'meditation',
    sounds: [
      { key: 'singing-bowls', name: 'Singing Bowls', note: 'two bowls, struck in turn', asset: require('../../../assets/sounds/singing-bowls.m4a') },
      { key: 'wind-chimes', name: 'Wind Chimes', note: 'high and unhurried', asset: require('../../../assets/sounds/wind-chimes.m4a') },
      { key: 'soft-drone', name: 'Soft Drone', note: 'one held chord', asset: require('../../../assets/sounds/soft-drone.m4a') }
    ]
  },
  {
    key: 'unique',
    label: 'unique',
    sounds: [
      { key: 'deep-space', name: 'Deep Space', note: 'a low hum, far away', asset: require('../../../assets/sounds/deep-space.m4a') },
      { key: 'dreamy-ambient', name: 'Dreamy Ambient', note: 'a slow, warm pad', asset: require('../../../assets/sounds/dreamy-ambient.m4a') },
      { key: 'monsoon-rain', name: 'Monsoon Rain', note: 'heavy rain and thunder', asset: require('../../../assets/sounds/monsoon-rain.m4a') }
    ]
  }
];

export const ALL_SOUNDS: readonly Sound[] = SOUND_CATEGORIES.flatMap(c => c.sounds);

/** The two player settings the calm sounds change. */
type Settable = { loop: boolean; volume: number };

/**
 * Sets them on an expo-audio player. Kept out of the component because the
 * player is a hook's return value, which React's rules treat as read-only
 * there — though the native player is designed to be set like this.
 */
export function configure(player: Settable, settings: Partial<Settable>): void {
  if (settings.loop !== undefined) player.loop = settings.loop;
  if (settings.volume !== undefined) player.volume = settings.volume;
}

/** Sleep timer choices, in minutes; null runs until stopped. */
export const TIMER_CHOICES = [null, 15, 30, 60] as const;
export type TimerChoice = (typeof TIMER_CHOICES)[number];

/** When a sleep timer set at `from` ends; null for no timer. */
export function timerEndsAt(choice: TimerChoice, from: number = Date.now()): number | null {
  return choice === null ? null : from + choice * 60_000;
}

/** How long the fade at the end of a sleep timer lasts. */
export const FADE_MS = 10_000;

/** Volume `elapsedMs` into the closing fade: 1 → 0 along a gentle curve. */
export function fadeVolume(elapsedMs: number): number {
  const x = Math.min(1, Math.max(0, elapsedMs / FADE_MS));
  return Math.cos((x * Math.PI) / 2) ** 2;
}
